### ISSUE TITLE
Changelog location for numpy 1.14.2

### ISSUE THREAD

**Issue by alexwlchan** [pyupio/changelogs#101]
https://github.com/HypothesisWorks/hypothesis-python/pull/1173 bumps numpy from 1.14.1 to 1.14.2, but is missing a changelog (despite numpy being apparently covered in #60).

There are changelogs in the numpy GitHub repo: https://github.com/numpy/numpy/tree/master/doc/changelog

**Comment by harlekeyn** [comment]
Thank you, Alex!
