### ISSUE TITLE
pytest changelog

### ISSUE THREAD

**Issue by lafrech** [pyupio/changelogs#102]
> This PR updates pytest from 3.4.2 to 3.5.0.
> 
> The bot wasn't able to find a changelog for this release. Got an idea?

There you go: https://docs.pytest.org/en/latest/changelog.html

**Comment by edmorley** [comment]
Also:
https://github.com/pytest-dev/pytest/blob/master/CHANGELOG.rst

**Comment by ntravis** [comment]
dupe of #68

**Comment by jayfk** [comment]
pytest should be working, just confirmed it via the CLI. Is it somehow possible that the changelog wasn't merged into master at the time of the release? 😕 

Investigating..

**Comment by jayfk** [comment]
> dupe of #68

👍
