### ISSUE TITLE
pbr changelog

### ISSUE THREAD

**Issue by amureki** [pyupio/changelogs#108]
Hi, I think, for [`pbr`](https://pypi.org/project/pbr/) releases we can use this link as a changelog:
https://docs.openstack.org/pbr/latest/user/history.html

P.S. As I side note, I want to propose [issue templates](https://blog.github.com/2016-02-17-issue-and-pull-request-templates/), so users would create issues like this in a single proper way maintainers want.

Thank you!

**Comment by harlekeyn** [comment]
Thank you!
