### ISSUE TITLE
gunicorn changelog location

### ISSUE THREAD

**Issue by leohemsted** [pyupio/changelogs#113]
https://pypi.org/project/gunicorn/

Changelogs can be found at: http://docs.gunicorn.org/en/stable/news.html

or the source at: https://github.com/benoitc/gunicorn/blob/master/docs/source/news.rst

**Comment by chris48s** [comment]
think this one is now fixed: https://pyup.io/changelogs/gunicorn/

**Comment by Kaligule** [comment]
I don't think it is fixed - the changelogs for versions don't appear there.
Latest version: 20.0.4
Latest version according to pyup: 19.9.0


It seems like the sites @leohemsted mentioned are up to date.

**Comment by harlekeyn** [comment]
Thank you all.
We'll use → https://raw.githubusercontent.com/benoitc/gunicorn/master/docs/source/news.rst
