### ISSUE TITLE
Changelog missing for pytest 3.6.2

### ISSUE THREAD

**Issue by edmorley** [pyupio/changelogs#127]
This PR to update pytest didn't have a changelog:
mozilla/treeherder#3685

But it exists here:
https://github.com/pytest-dev/pytest/blob/master/CHANGELOG.rst#pytest-362-2018-06-20
https://github.com/pytest-dev/pytest/blob/3.6.2/CHANGELOG.rst#pytest-362-2018-06-20
https://docs.pytest.org/en/latest/changelog.html#pytest-3-6-2-2018-06-20

**Comment by edmorley** [comment]
Sorry dupe of #68

**Comment by pzelnip** [comment]
Also reported in #216  #210 #158 #127 #68

**Comment by harlekeyn** [comment]
Thanks for this!
