### ISSUE TITLE
Newrelic release notes

### ISSUE THREAD

**Issue by jezdez** [pyupio/changelogs#14]
https://docs.newrelic.com/docs/release-notes/agent-release-notes/python-release-notes

**Comment by jayfk** [comment]
This will be a tough one as the parser currently has no HTML support, I'll see what I can do!

**Comment by edmorley** [comment]
Perhaps an alternative is to just link to the release notes page (eg https://docs.newrelic.com/docs/release-notes/agent-release-notes/python-release-notes/python-agent-282163), as a fake release notes entry?

**Comment by edmorley** [comment]
In the meantime, you're welcome to point at my mirror of the newrelic agent source, which I use to be able to diff the versions and tag/release appropriately:
https://github.com/edmorley/newrelic-python-agent/releases

**Comment by edmorley** [comment]
Many thanks!
