### ISSUE TITLE
Error: "The bot wasn't able to find a changelog for this release." for invoke=1.2.0 (PyInvoke)

### ISSUE THREAD

**Issue by shlomiLan** [pyupio/changelogs#147]
The changelog for pyinvoke is [here](https://www.pyinvoke.org/changelog.html#1.2.0)

Please let me know if there is more info that I can provide.

**Comment by harlekeyn** [comment]
The versions on your link to not match with the ones on https://pypi.org/project/pyinvoke/#history
Any idea what is going on?

**Comment by shlomiLan** [comment]
Hey @harlekeyn,

You are looking at the wrong package, the right package is: https://pypi.org/project/invoke/#history
Note that there is `pyinvoke` and `invoke`, 2 different packages and we need `invoke`.
Also, this is a very old post, not sure if it's still relevant.

Thanks

**Comment by harlekeyn** [comment]
Thanks, that's very helpful. We'll process this.
