### ISSUE TITLE
django-jsonfield changelog

### ISSUE THREAD

**Issue by tomhamiltonstubber** [pyupio/changelogs#15]
Bit of an annoying one to get, but if you can be motivated:

https://github.com/bradjasper/django-jsonfield/

It's in the readme.

**Comment by jayfk** [comment]
Maybe we can fix this upstream: https://github.com/bradjasper/django-jsonfield/pull/180

**Comment by tomhamiltonstubber** [comment]
Very efficient! Nice one lads.

bradjasper/django-jsonfield#180.
