### ISSUE TITLE
Changelog for pdfminer.six to 20181108

### ISSUE THREAD

**Issue by WtfJoke** [pyupio/changelogs#165]
The changelog can be seen here:
https://github.com/pdfminer/pdfminer.six/releases/tag/20181108

Or in generally probably here:
https://github.com/pdfminer/pdfminer.six/blob/master/CHANGELOG.md

E.g.

> 
> List of changes
> Version 20181108
> 
>     PR #141 to speedup layout analysis
>     PR #173 for using argparse and replace deprecated getopt
>     PR #142 to compile pdfminer.six with cython, successfully
>

**Comment by harlekeyn** [comment]
Added. Thank you.
