### ISSUE TITLE
I don’t want to do upgrades that break Python 2 compatibility

### ISSUE THREAD

**Issue by cclauss** [pyupio/changelogs#167]
For the next 400 days my project needs to support both Python 2 and Python 3.  Current pyup  reports show me Python 3 compatibility but they do not warn me about which upgrades will break compatibility with Python 2.  It would be helpful if pyup reports had Py2 and Py3 columns so I can be sure that my requirements support both.

**Comment by orsinium** [comment]
> For the next 400 days

I hope this issue isn't actual anymore :upside_down_face:

**Comment by cclauss** [comment]
Thx
