### ISSUE TITLE
Wrong changelog for python msgpack

### ISSUE THREAD

**Issue by fake-name** [pyupio/changelogs#178]
Right now, the changelog for msgpack is pointed to... somewhere. See https://pyup.io/changelogs/msgpack/. It somehow contains a bunch of revisions that have nothing to do with the actual project in question.

I have no idea where this stuff is coming from, but the correct changelog is https://github.com/msgpack/msgpack-python/blob/master/ChangeLog.rst

**Comment by harlekeyn** [comment]
Thank you!
