### ISSUE TITLE
pandas changelog

### ISSUE THREAD

**Issue by Harmon758** [pyupio/changelogs#180]
https://pandas.pydata.org/pandas-docs/stable/whatsnew/index.html
https://github.com/pandas-dev/pandas/tree/master/doc/source/whatsnew

https://github.com/pyupio/changelogs/commit/27d7633b1dfdc2a7a02ae94233284db0aea025b7 specifically checks for .txt files, and seems to have been broken by https://github.com/pandas-dev/pandas/commit/e413c491e090274aad78489cc17a2e29cbd8e269 (https://github.com/pandas-dev/pandas/pull/21599).

**Comment by harlekeyn** [comment]
Thanks.
