### ISSUE TITLE
aiohttp

### ISSUE THREAD

**Issue by samuelcolvin** [pyupio/changelogs#19]
https://github.com/aio-libs/aiohttp/blob/master/HISTORY.rst

Looks pretty standard, I assumed the reason changelogs didn't pick this up was the change of organisation for the repo, but the repo appears to be correct in pyup's pull request.

**Comment by jayfk** [comment]
That should've worked. Could you point me to a PR that failed to provide the changelog?

Looks like they keep two changelogs:

- https://github.com/aio-libs/aiohttp/blob/master/CHANGES.rst
- https://github.com/aio-libs/aiohttp/blob/master/HISTORY.rst

Data looks okay on pyup.io: https://pyup.io/changelogs/aiohttp/

**Comment by samuelcolvin** [comment]
https://github.com/tutorcruncher/socket-server/pull/43

**Comment by jayfk** [comment]
Ah. It looks like there's no entry for the `1.3.5` release.

The latest release in https://github.com/aio-libs/aiohttp/blob/master/HISTORY.rst is `1.3.4` and https://github.com/aio-libs/aiohttp/blob/master/CHANGES.rst begins at `2.0.0rc1`.

Raised an issue here: https://github.com/aio-libs/aiohttp/issues/1730

**Comment by jayfk** [comment]
This should work now. Thanks @samuelcolvin and @fafhrd91.
