### ISSUE TITLE
Add support for HTML changelogs

### ISSUE THREAD

**Issue by jayfk** [pyupio/changelogs#2]
Slacks [slacklient](https://github.com/slackapi/python-slackclient) is using a HTML changelog. It'd great if we could support that.

cc @roach

**Comment by jayfk** [comment]
Turns out I was a bit too fast. Fetching slackclient's changelog is just a matter of adding `docs-src` to `DOCS_CANDIDATES`.

Sorry for the noise!

**Comment by Roach** [comment]
🎉

**Comment by jayfk** [comment]
Fixed in https://github.com/pyupio/changelogs/commit/bdff64c9ccb454a338d26ff1b3f414893418f4c0

Looking good: https://pyup.io/changelogs/slackclient/
