### ISSUE TITLE
pylib changelog

### ISSUE THREAD

**Issue by The-Compiler** [pyupio/changelogs#21]
pyup.io finds a [changelog](https://pyup.io/changelogs/py/) for pylib (aka `py`), but it doesn't contain the newest 1.4.33 release. Maybe it picks up the changelog from before the BitBucket -> GitHub migration of py somehow?

The official changelog is [this one](https://github.com/pytest-dev/py/blob/master/CHANGELOG) or [this one](http://py.readthedocs.io/en/latest/changelog.html#changelog) FWIW, and they contain 1.4.33.

**Comment by jayfk** [comment]
Ah, that's a weird one. The parser uses the old `bugtrack_url` as a starting point to look for the changelog.

I've raised an [issue](https://github.com/pytest-dev/py/issues/117) on upstream. Let's give them a couple of days to update it.

**Comment by jayfk** [comment]
Okay, I've added a custom parser. That's probably the easiest thing to do right now.

**Comment by The-Compiler** [comment]
I updated the `bugtrack_url`, so I think the custom parser isn't needed anymore now.
