### ISSUE TITLE
PyAudio changelog

### ISSUE THREAD

**Issue by jacobtomlinson** [pyupio/changelogs#22]
It is possible to find a changelog for PyAudio at http://people.csail.mit.edu/hubert/pyaudio/.

**Comment by jayfk** [comment]
Thanks! This will probably be hard to parse, going to need to write a custom parser.

Raw changelog URL: https://people.csail.mit.edu/hubert/git/?p=pyaudio.git;a=blob_plain;f=CHANGELOG;hb=master
