### ISSUE TITLE
numpy/releases

### ISSUE THREAD

**Issue by cclauss** [pyupio/changelogs#227]
https://github.com/numpy/numpy/releases

**Comment by harlekeyn** [comment]
Thank you.

**Comment by nasifimtiazohi** [comment]
Why is this issue closed? The package still seems to van't find release notes for `numpy`.

**Comment by yeisonvargasf** [comment]
Hi @nasifimtiazohi , you are right, there is a PR with the fix for this issue, it's waiting to be deployed.
