### ISSUE TITLE
extract changes from Github Release body text? 

### ISSUE THREAD

**Issue by anthrotype** [pyupio/changelogs#236]
Hello

In our projects, we like to write release notes in the annotated git tag message, which is then used as the content for the Github Release notes.

E.g. see the latest one here: https://github.com/googlefonts/picosvg/releases/tag/v0.7.3

It would be great pyup bot could extract the changelog from the Github Releases notes. I'm surprised it doesn't do it already.

Am I doing something wrong?

Thank you

**Comment by harlekeyn** [comment]
Thank you, @anthrotype. I'll discuss it with the team.
