### ISSUE TITLE
PyPI: Changelogs for newrelic

### ISSUE THREAD

**Issue by edmorley** [pyupio/changelogs#26]
https://pypi.python.org/pypi/newrelic

The release notes overview is at:
https://docs.newrelic.com/docs/release-notes/agent-release-notes/python-release-notes

The per-release pages have URLs of form:
https://docs.newrelic.com/docs/release-notes/agent-release-notes/python-release-notes/python-agent-282163

...where '282163' is the full version string (eg '2.82.1.63') with periods removed.

**Comment by edmorley** [comment]
Oh sorry, dupe of #14.

**Comment by jayfk** [comment]
Closing this as a dupe. Probably need to add a HTML parser sooner or later =/.
