### ISSUE TITLE
Changelog missing latest version for django-cors-headers

### ISSUE THREAD

**Issue by edmorley** [pyupio/changelogs#28]
https://pyup.io/changelogs/django-cors-headers/ says the newest version is 2.0.1.

However https://github.com/ottoyiu/django-cors-headers/blob/259181ca7a554183b15efd786850e09f6901da20/HISTORY.rst lists the latest PyPI version of 2.0.2.

**Comment by jayfk** [comment]
Looks like 2.0.2 wasn't available on the last fetch, there was a typo: https://github.com/ottoyiu/django-cors-headers/pull/211/files

**Comment by edmorley** [comment]
Ah makes sense, thank you :-)
