### ISSUE TITLE
Support changelogs in GitHub release descriptions

### ISSUE THREAD

**Issue by edmorley** [pyupio/changelogs#29]
A number of packages use the GitHub "releases" feature to describe the changes in that release (and don't have a separate changelog file at all).

For example:
https://github.com/syrusakbary/promise/releases
https://github.com/graphql-python/graphql-core/releases
https://github.com/graphql-python/graphene-django/releases
https://github.com/google/brotli/releases

**Comment by jayfk** [comment]
Yeah. I have this working in a local branch, but haven't found a way to strip out oAuth tokens that are recorded by betamax.

**Comment by jayfk** [comment]
This is not live and needs a couple more tests. Reopening.

**Comment by jayfk** [comment]
Now deploying 👏

**Comment by edmorley** [comment]
Many thanks!
