### ISSUE TITLE
pyup not finding changelog

### ISSUE THREAD

**Issue by cuducos** [pyupio/changelogs#3]
* changelogger version: 0.5.0
* Python version: 3.5.2
* Operating System: macOS Sierra

### Description

I'm maintain a couple of PyPI packages ([webassets-elm](https://github.com/cuducos/webassets-elm), for example) but everytime pyup opens a PR (in repositories that use my package) it says it can't find any changelog.

### What I Did

I installed `changelogs` and tested it, but always had an empty stdout. My changelog is the `CHANGELOG` file in the root of the repo, but I tried renaming and moving it all around (no success):

```console
$ ls -laGh | grep CHANGELOG
-rw-r--r--@  1 cuducos  staff   362B Jan 27 13:17 CHANGELOG
$ changelogs webassets_elm
$ git mv CHANGELOG changelog.md
$ changelogs webassets_elm
$ gt mv changelog.md changelog
$ changelogs webassets_elm
$ git mv changelog.md webassets_elm/CHANGELOG
$ changelogs webassets_elm
$
```
Am I missing anything or is this a bug?

**Comment by jayfk** [comment]
The parser is unable to parse the changelog as it discards all lines beginning with `*` (while looking for a release head).

It's horrible, but overall it works better this way. If you want to see the reasoning behind this, take a look at the horrible world of changelog parsing here: https://github.com/pyupio/changelogs/blob/master/changelogs/parser.py#L36

**Comment by cuducos** [comment]
Good to know! It works now. Many thanks, @jayfk ; )

**Comment by jayfk** [comment]
Great. I'll have to trigger this manually for pyup.io to fetch the new changelog.

**Comment by cuducos** [comment]
> the horrible world of changelog parsing here

Horrible but well commented in the source code — thanks for that too ; )

> Great. I'll have to trigger this manually for pyup.io to fetch the new changelog.

We can wait for the next update, no worries ; )
