### ISSUE TITLE
Fall back to raw commit logs as a last resort

### ISSUE THREAD

**Issue by jayfk** [pyupio/changelogs#34]

**Comment by jayfk** [comment]
I've added this in https://github.com/pyupio/changelogs/commit/2b1f13d319f77d05ef2ceee0362f0347f87bdc2c

**Comment by jayfk** [comment]
Tests are running locally, but failing on Travis.

**Comment by jayfk** [comment]
After deleting @hackebrot's home user folder, the test has been disabled. ¯\\__(ツ)_/¯

**Comment by hackebrot** [comment]
💥 🏠 💥 😞
