### ISSUE TITLE
pbr

### ISSUE THREAD

**Issue by peterbe** [pyupio/changelogs#37]
History is here: https://docs.openstack.org/developer/pbr/history.html

**Comment by alexkiro** [comment]
Probably tricky one, since PBR is used to generate changelog from Git log, we don't have a rst/md/txt file to parse. 

So not really sure if this should (a) parse the HTML from the link (b) generate the changelog from git log as well.

**Comment by jayfk** [comment]
As @jezdez mentions in https://bugs.launchpad.net/pbr/+bug/1681725 `pbr` is a huge dependency on many projects.

This probably justifies some dirty screen scraping here :)
