### ISSUE TITLE
openpyxl changelog is flunked

### ISSUE THREAD

**Issue by jayfk** [pyupio/changelogs#4]

**Comment by jayfk** [comment]
Offending line seems to be

```
Tests run on Python 2.5, 2.6, 2.7, 3.2, 3.3
```

Source:

https://bitbucket.org/openpyxl/openpyxl/src/5961d9dc9e51d70824b40517d52103cb4fd7c673/doc/changes.rst?at=default&fileviewer=file-view-default

**Comment by jayfk** [comment]
fixed in https://github.com/pyupio/changelogs/commit/38854ac37f0c102f3fe557432b7d2e207b178d70, cc @samuelcolvin

**Comment by samuelcolvin** [comment]
great work. Thanks.
