### ISSUE TITLE
BeautifulSoup4 release notes

### ISSUE THREAD

**Issue by gtback** [pyupio/changelogs#46]
https://bazaar.launchpad.net/~leonardr/beautifulsoup/bs4/view/head:/NEWS.txt

**Comment by jayfk** [comment]
thanks!

**Comment by M157q** [comment]
The link above now returns `404 Not Found`.
CHANGELOG of beautifulsoup4 has been moved to here: https://bazaar.launchpad.net/~leonardr/beautifulsoup/bs4/view/head:/CHANGELOG
