### ISSUE TITLE
lazy-object-proxy changelog

### ISSUE THREAD

**Issue by The-Compiler** [pyupio/changelogs#48]
Either [on PyPI](https://pypi.python.org/pypi/lazy-object-proxy) or [readthedocs](https://python-lazy-object-proxy.readthedocs.io/en/latest/changelog.html) or [GitHub](https://github.com/ionelmc/python-lazy-object-proxy/blob/master/CHANGELOG.rst)

**Comment by jayfk** [comment]
Thanks 👍
