### ISSUE TITLE
[changelog] Where you can find the changelog of django-tastypie

### ISSUE THREAD

**Issue by jfunez** [pyupio/changelogs#65]
Hi, 

Each release has a specific page of changelog.

Here you can find all:
https://django-tastypie.readthedocs.io/en/latest/release_notes/index.html

As the latest release is: v0.14.0 the page is:
https://django-tastypie.readthedocs.io/en/latest/release_notes/v0.14.0.html

Also you can find the same page at github:
https://github.com/django-tastypie/django-tastypie/blob/master/docs/release_notes/v0.14.0.rst

HTH! and thanks for your great work!

**Comment by harlekeyn** [comment]
Thanks.
