### ISSUE TITLE
Changelog for pytest

### ISSUE THREAD

**Issue by jetheurer** [pyupio/changelogs#68]
Looks like the changelog is here: https://docs.pytest.org/en/latest/changelog.html

**Comment by EnTeQuAk** [comment]
the changelog is also in the git repository: https://github.com/pytest-dev/pytest/blob/master/CHANGELOG.rst

**Comment by pzelnip** [comment]
Also reported in #216  #210 #158 #127 #68

**Comment by harlekeyn** [comment]
Received, thanks.
