### ISSUE TITLE
djangorestframework

### ISSUE THREAD

**Issue by snopoke** [pyupio/changelogs#7]
http://www.django-rest-framework.org/topics/release-notes/#35x-series

**Comment by jayfk** [comment]
thanks @snopoke

**Comment by jayfk** [comment]
Reopening this. There seems to be a problem with the 3.6.x releases.

**Comment by jayfk** [comment]
The 3.6.x release notes seem to be missing, raised an issue here: https://github.com/tomchristie/django-rest-framework/issues/4962

**Comment by jayfk** [comment]
This is working now 👍
