### ISSUE TITLE
Changelog for libtmux

### ISSUE THREAD

**Issue by tony** [pyupio/changelogs#70]
https://github.com/tony/libtmux/blob/master/CHANGES

format: https://github.com/bitprophet/releases / http://releases.readthedocs.io/

other projects:

- https://github.com/tony/tmuxp/blob/master/CHANGES
- https://github.com/tony/vcspull/blob/master/CHANGES
- https://github.com/tony/libvcs/blob/master/CHANGES
- https://github.com/cihai/cihai/blob/master/CHANGES

**Comment by harlekeyn** [comment]
Thanks.
