### ISSUE TITLE
python-dotenv changelog

### ISSUE THREAD

**Issue by fedorareis** [pyupio/changelogs#78]
The python-dotenv changelogs can be found at https://github.com/theskumar/python-dotenv#changelog

**Comment by Harmon758** [comment]
https://pyup.io/changelogs/python-dotenv/ currently seems to be referring to https://github.com/jpadilla/django-dotenv/releases.

**Comment by fedorareis** [comment]
Based on the comment by @Harmon758 it sounds like the changelog for python-dotenv needs to be fixed and an entry needs to be added for django-dotenv

**Comment by harlekeyn** [comment]
Thank you all.
