### ISSUE TITLE
markdown changelog location

### ISSUE THREAD

**Issue by nikolas** [pyupio/changelogs#85]
https://github.com/Python-Markdown/markdown/releases

**Comment by benjaoming** [comment]
That's not really a changelog :)

But the change log is pretty unconventional, so might not be easy to parse: https://github.com/Python-Markdown/markdown/tree/master/docs/change_log

**Comment by nikolas** [comment]
Yeah, it looks like they've only added a description in the most recent release, which is only coming through as part of the commit message :/

**Comment by harlekeyn** [comment]
Thanks.
