### ISSUE TITLE
Cannot load HISTORY file in satelliteQE/robozilla/

### ISSUE THREAD

**Issue by rochacbruno** [pyupio/changelogs#90]
Hi,

we have a `HISTORY` plain text file located on the root of https://github.com/SatelliteQE/robozilla/blob/master/HISTORY

It is not showing on PR https://github.com/SatelliteQE/robottelo/pull/5733
is there something wrong with `HISTORY` file?

**Comment by jayfk** [comment]
There's no real convention for writing a changelog file. The one used on robozilla is failing on the default parser. I've added a new one, should be good to go now.

**Comment by rochacbruno** [comment]
@jayfk thanks, we used to have it in .rst format so I just removed the ,rst extension
